name = "meraki-dashboard-ha"
compatibility_date = "2025-04-01"
routes = [
  { pattern = "m7kni.io/meraki-dashboard-ha/*", custom_domain = true }
]

[assets]
directory = "./site"
not_found_handling = "404-page"

[observability.logs]
enabled = true
