"""Constants for the Meraki Dashboard integration.

This module provides backward compatibility for existing constants while 
importing from the new structured configuration system.
"""

from typing import Final

from .config.constants import (
    API_CONFIG,
    DEVICE_TYPE_CONFIG,
    DEVICE_TYPES,
    EVENT_CONFIG,
    REFRESH_INTERVALS,
    SCAN_INTERVALS,
    SENSOR_METRICS,
    ApiConfiguration,
    DeviceTypeConfiguration,
    EventConfiguration,
    MerakiDeviceTypes,
    RefreshIntervals,
    ScanIntervals,
    SensorMetrics,
)

DOMAIN: Final = "meraki_dashboard"

# Configuration and options
CONF_API_KEY: Final = "api_key"
CONF_BASE_URL: Final = "base_url"
CONF_ORGANIZATION_ID: Final = "organization_id"
CONF_NETWORKS: Final = "networks"
CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_SELECTED_DEVICES: Final = "selected_devices"
CONF_AUTO_DISCOVERY: Final = "auto_discovery"
CONF_DISCOVERY_INTERVAL: Final = "discovery_interval"

# Per-hub configuration keys
CONF_HUB_SCAN_INTERVALS: Final = "hub_scan_intervals"
CONF_HUB_DISCOVERY_INTERVALS: Final = "hub_discovery_intervals"
CONF_HUB_AUTO_DISCOVERY: Final = "hub_auto_discovery"

# Configuration keys for tiered refresh
CONF_STATIC_DATA_INTERVAL: Final = "static_data_interval"
CONF_SEMI_STATIC_DATA_INTERVAL: Final = "semi_static_data_interval"
CONF_DYNAMIC_DATA_INTERVAL: Final = "dynamic_data_interval"

# Defaults
DEFAULT_NAME: Final = "Meraki Dashboard"

# Import from structured configuration for backward compatibility
USER_AGENT: Final = API_CONFIG.USER_AGENT
DEFAULT_BASE_URL: Final = API_CONFIG.DEFAULT_BASE_URL
REGIONAL_BASE_URLS: Final = API_CONFIG.REGIONAL_BASE_URLS

DEFAULT_SCAN_INTERVAL: Final = SCAN_INTERVALS.DEFAULT_SCAN
MIN_SCAN_INTERVAL: Final = SCAN_INTERVALS.MIN_SCAN
DEFAULT_DISCOVERY_INTERVAL: Final = SCAN_INTERVALS.DEFAULT_DISCOVERY
MIN_DISCOVERY_INTERVAL: Final = SCAN_INTERVALS.MIN_DISCOVERY

# Device types - import from structured configuration
SENSOR_TYPE_MT: Final = DEVICE_TYPES.MT
SENSOR_TYPE_MR: Final = DEVICE_TYPES.MR  
SENSOR_TYPE_MS: Final = DEVICE_TYPES.MS
SENSOR_TYPE_MV: Final = DEVICE_TYPES.MV

# Scan intervals - import from structured configuration
DEVICE_TYPE_SCAN_INTERVALS: Final = SCAN_INTERVALS.DEVICE_TYPE_INTERVALS
DEFAULT_SCAN_INTERVAL_MINUTES: Final = SCAN_INTERVALS.DEFAULT_UI_INTERVALS
DEFAULT_DISCOVERY_INTERVAL_MINUTES: Final = SCAN_INTERVALS.DEFAULT_DISCOVERY_MINUTES
MIN_SCAN_INTERVAL_MINUTES: Final = SCAN_INTERVALS.MIN_SCAN_MINUTES
MIN_DISCOVERY_INTERVAL_MINUTES: Final = SCAN_INTERVALS.MIN_DISCOVERY_MINUTES

# Device type mappings - import from structured configuration
DEVICE_TYPE_MAPPINGS: Final = DEVICE_TYPE_CONFIG.MAPPINGS

# Hub type constants
HUB_TYPE_ORGANIZATION: Final = "organization"
HUB_TYPE_NETWORK: Final = "network"

# Organization hub suffix
ORG_HUB_SUFFIX: Final = "Organisation"

# Sensor metrics - import from structured configuration
# MT (Environmental) sensor metrics
MT_SENSOR_APPARENT_POWER: Final = SENSOR_METRICS.MT_APPARENT_POWER
MT_SENSOR_BATTERY: Final = SENSOR_METRICS.MT_BATTERY
MT_SENSOR_BUTTON: Final = SENSOR_METRICS.MT_BUTTON
MT_SENSOR_CO2: Final = SENSOR_METRICS.MT_CO2
MT_SENSOR_CURRENT: Final = SENSOR_METRICS.MT_CURRENT
MT_SENSOR_DOOR: Final = SENSOR_METRICS.MT_DOOR
MT_SENSOR_DOWNSTREAM_POWER: Final = SENSOR_METRICS.MT_DOWNSTREAM_POWER
MT_SENSOR_FREQUENCY: Final = SENSOR_METRICS.MT_FREQUENCY
MT_SENSOR_HUMIDITY: Final = SENSOR_METRICS.MT_HUMIDITY
MT_SENSOR_INDOOR_AIR_QUALITY: Final = SENSOR_METRICS.MT_INDOOR_AIR_QUALITY
MT_SENSOR_NOISE: Final = SENSOR_METRICS.MT_NOISE
MT_SENSOR_PM25: Final = SENSOR_METRICS.MT_PM25
MT_SENSOR_POWER_FACTOR: Final = SENSOR_METRICS.MT_POWER_FACTOR
MT_SENSOR_REAL_POWER: Final = SENSOR_METRICS.MT_REAL_POWER
MT_SENSOR_REMOTE_LOCKOUT_SWITCH: Final = SENSOR_METRICS.MT_REMOTE_LOCKOUT_SWITCH
MT_SENSOR_TEMPERATURE: Final = SENSOR_METRICS.MT_TEMPERATURE
MT_SENSOR_TVOC: Final = SENSOR_METRICS.MT_TVOC
MT_SENSOR_VOLTAGE: Final = SENSOR_METRICS.MT_VOLTAGE
MT_SENSOR_WATER: Final = SENSOR_METRICS.MT_WATER

# MR (Wireless) sensor metrics
MR_SENSOR_SSID_COUNT: Final = SENSOR_METRICS.MR_SSID_COUNT
MR_SENSOR_ENABLED_SSIDS: Final = SENSOR_METRICS.MR_ENABLED_SSIDS
MR_SENSOR_OPEN_SSIDS: Final = SENSOR_METRICS.MR_OPEN_SSIDS
MR_SENSOR_CLIENT_COUNT: Final = SENSOR_METRICS.MR_CLIENT_COUNT
MR_SENSOR_CHANNEL_UTILIZATION_2_4: Final = SENSOR_METRICS.MR_CHANNEL_UTILIZATION_2_4
MR_SENSOR_CHANNEL_UTILIZATION_5: Final = SENSOR_METRICS.MR_CHANNEL_UTILIZATION_5
MR_SENSOR_DATA_RATE_2_4: Final = SENSOR_METRICS.MR_DATA_RATE_2_4
MR_SENSOR_DATA_RATE_5: Final = SENSOR_METRICS.MR_DATA_RATE_5
MR_SENSOR_CONNECTION_SUCCESS_RATE: Final = SENSOR_METRICS.MR_CONNECTION_SUCCESS_RATE
MR_SENSOR_CONNECTION_FAILURES: Final = SENSOR_METRICS.MR_CONNECTION_FAILURES
MR_SENSOR_TRAFFIC_SENT: Final = SENSOR_METRICS.MR_TRAFFIC_SENT
MR_SENSOR_TRAFFIC_RECV: Final = SENSOR_METRICS.MR_TRAFFIC_RECV
MR_SENSOR_RF_POWER: Final = SENSOR_METRICS.MR_RF_POWER
MR_SENSOR_RF_POWER_2_4: Final = SENSOR_METRICS.MR_RF_POWER_2_4
MR_SENSOR_RF_POWER_5: Final = SENSOR_METRICS.MR_RF_POWER_5
MR_SENSOR_RADIO_CHANNEL_2_4: Final = SENSOR_METRICS.MR_RADIO_CHANNEL_2_4
MR_SENSOR_RADIO_CHANNEL_5: Final = SENSOR_METRICS.MR_RADIO_CHANNEL_5
MR_SENSOR_CHANNEL_WIDTH_5: Final = SENSOR_METRICS.MR_CHANNEL_WIDTH_5
MR_SENSOR_RF_PROFILE_ID: Final = SENSOR_METRICS.MR_RF_PROFILE_ID
MR_SENSOR_MEMORY_USAGE: Final = SENSOR_METRICS.MR_MEMORY_USAGE

# MS (Switch) sensor metrics
MS_SENSOR_PORT_COUNT: Final = SENSOR_METRICS.MS_PORT_COUNT
MS_SENSOR_CONNECTED_PORTS: Final = SENSOR_METRICS.MS_CONNECTED_PORTS
MS_SENSOR_POE_PORTS: Final = SENSOR_METRICS.MS_POE_PORTS
MS_SENSOR_PORT_UTILIZATION_SENT: Final = SENSOR_METRICS.MS_PORT_UTILIZATION_SENT
MS_SENSOR_PORT_UTILIZATION_RECV: Final = SENSOR_METRICS.MS_PORT_UTILIZATION_RECV
MS_SENSOR_PORT_TRAFFIC_SENT: Final = SENSOR_METRICS.MS_PORT_TRAFFIC_SENT
MS_SENSOR_PORT_TRAFFIC_RECV: Final = SENSOR_METRICS.MS_PORT_TRAFFIC_RECV
MS_SENSOR_POE_POWER: Final = SENSOR_METRICS.MS_POE_POWER
MS_SENSOR_CONNECTED_CLIENTS: Final = SENSOR_METRICS.MS_CONNECTED_CLIENTS
MS_SENSOR_POWER_MODULE_STATUS: Final = SENSOR_METRICS.MS_POWER_MODULE_STATUS
MS_SENSOR_PORT_ERRORS: Final = SENSOR_METRICS.MS_PORT_ERRORS
MS_SENSOR_PORT_DISCARDS: Final = SENSOR_METRICS.MS_PORT_DISCARDS
MS_SENSOR_PORT_LINK_COUNT: Final = SENSOR_METRICS.MS_PORT_LINK_COUNT
MS_SENSOR_POE_LIMIT: Final = SENSOR_METRICS.MS_POE_LIMIT
MS_SENSOR_PORT_UTILIZATION: Final = SENSOR_METRICS.MS_PORT_UTILIZATION
MS_SENSOR_MEMORY_USAGE: Final = SENSOR_METRICS.MS_MEMORY_USAGE

# Organization-level metrics
ORG_SENSOR_DEVICE_STATUS: Final = SENSOR_METRICS.ORG_DEVICE_STATUS
ORG_SENSOR_LICENSE_INVENTORY: Final = SENSOR_METRICS.ORG_LICENSE_INVENTORY
ORG_SENSOR_LICENSE_EXPIRING: Final = SENSOR_METRICS.ORG_LICENSE_EXPIRING
ORG_SENSOR_RECENT_ALERTS: Final = SENSOR_METRICS.ORG_RECENT_ALERTS
ORG_SENSOR_UPLINK_STATUS: Final = SENSOR_METRICS.ORG_UPLINK_STATUS

# Sensor groupings - import from structured configuration
MT_POWER_SENSORS: Final = SENSOR_METRICS.MT_POWER_SENSORS
MT_BINARY_SENSOR_METRICS: Final = SENSOR_METRICS.MT_BINARY_SENSOR_METRICS
MT_EVENT_SENSOR_METRICS: Final = SENSOR_METRICS.MT_EVENT_SENSOR_METRICS

# Event configuration - import from structured configuration
EVENT_TYPE: Final = EVENT_CONFIG.EVENT_TYPE
EVENT_DEVICE_ID: Final = EVENT_CONFIG.DEVICE_ID
EVENT_DEVICE_SERIAL: Final = EVENT_CONFIG.DEVICE_SERIAL
EVENT_SENSOR_TYPE: Final = EVENT_CONFIG.SENSOR_TYPE
EVENT_VALUE: Final = EVENT_CONFIG.VALUE
EVENT_PREVIOUS_VALUE: Final = EVENT_CONFIG.PREVIOUS_VALUE
EVENT_TIMESTAMP: Final = EVENT_CONFIG.TIMESTAMP

# Attributes
ATTR_NETWORK_ID: Final = "network_id"
ATTR_NETWORK_NAME: Final = "network_name"
ATTR_SERIAL: Final = "serial"
ATTR_MODEL: Final = "model"
ATTR_LAST_REPORTED_AT: Final = "last_reported_at"

# Tiered refresh intervals - import from structured configuration
STATIC_DATA_REFRESH_INTERVAL: Final = REFRESH_INTERVALS.STATIC_DATA
STATIC_DATA_REFRESH_INTERVAL_MINUTES: Final = REFRESH_INTERVALS.STATIC_DATA_MINUTES
SEMI_STATIC_DATA_REFRESH_INTERVAL: Final = REFRESH_INTERVALS.SEMI_STATIC_DATA
SEMI_STATIC_DATA_REFRESH_INTERVAL_MINUTES: Final = REFRESH_INTERVALS.SEMI_STATIC_DATA_MINUTES
DYNAMIC_DATA_REFRESH_INTERVAL: Final = REFRESH_INTERVALS.DYNAMIC_DATA
DYNAMIC_DATA_REFRESH_INTERVAL_MINUTES: Final = REFRESH_INTERVALS.DYNAMIC_DATA_MINUTES

# Data type classifications - import from structured configuration
STATIC_DATA_TYPES: Final = REFRESH_INTERVALS.STATIC_DATA_TYPES
SEMI_STATIC_DATA_TYPES: Final = REFRESH_INTERVALS.SEMI_STATIC_DATA_TYPES
DYNAMIC_DATA_TYPES: Final = REFRESH_INTERVALS.DYNAMIC_DATA_TYPES
