name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@afb6465863055fdc848fc71c8ef94af0aa813f42 # v1.20.1
