name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@afb6465863055fdc848fc71c8ef94af0aa813f42 # v1.20.1
