name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue! 🎉
            
            To help us help you, please make sure you've provided:
            - A clear description of the issue
            - Your Home Assistant version
            - Your integration version (check HACS or manual installation)
            - Relevant logs from Home Assistant (with sensitive info removed)
            - Steps to reproduce the issue
            
            Please also check our [troubleshooting guide](docs/troubleshooting.md) and [FAQ](docs/faq.md) first.
            
            We appreciate your contribution to making this integration better!
          pr-message: |
            Thanks for your first pull request! 🚀
            
            Before we can review your PR, please make sure:
            - [ ] Your code follows our [style guide](PYTHON_STYLE_GUIDE.md)
            - [ ] You've tested your changes with a real Home Assistant instance
            - [ ] You've added/updated tests if applicable
            - [ ] You've updated documentation if needed
            - [ ] Your commit messages follow [conventional commits](https://www.conventionalcommits.org/)
            
            Our CI will run some automated checks. If they fail, please check the logs and fix any issues.
            
            Thanks for contributing to the Meraki Dashboard Home Assistant integration! 