name: Trigger Documentation Sync

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'wrangler.toml'
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation sync in parent repo
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.DOCS_SYNC_PAT }}
          repository: rknightion/m7kni-net-site
          event-type: docs-update
          client-payload: '{"repository": "meraki-dashboard-ha"}'